### ISSUE TITLE
Apache Kafka Is Not Messaging!

### ISSUE THREAD

**Issue by riferrei** [gunnarmorling/awesome-opensource-data-engineering#4]
I know this may come as a surprise for many people but Apache Kafka _is not_ a messaging infrastructure. It is simpler to label it as such because it has been known this way since the project was born many years ago; but the reality is that today Kafka is more than that. _Kafka is a distributed streaming platform_.

![image](https://user-images.githubusercontent.com/35476/74441723-55a46f00-4e3e-11ea-8626-ceebb283e72d.png)

A streaming platform has three key capabilities:

- Publish and subscribe to streams of records, _similar to a message queue or enterprise messaging_ system.

- Store streams of records in a fault-tolerant durable way.

- Process streams of records as they occur.

Reference: https://kafka.apache.org/documentation/#gettingStarted

That means that Kafka should belong to the categories "Integration", "Messaging Infrastructure", and "Stream Processing" at the same time. Knowing that this would look odd on this list of open-source projects, I would suggest creating a new category called "Distributed Streaming Platforms" and put Kafka on it.

-- @riferrei

**Comment by gunnarmorling** [comment]
> Knowing that this would look odd on this list of open-source projects

Yeah, I think adding one project to multiple categories could be confusing. I had added Kafka Streams already separately. While it's part of the Kafka umbrella, it felt "separate enough" to me, and as you say it checks the streaming box. Would it help to list Kafka Connect under "Integration"?

> a new category called "Distributed Streaming Platforms" 

That's certainly an option. What other projects would be in there, Apache Pulsar maybe?

**Comment by riferrei** [comment]
Yeah I think adding Kafka Connect to "Integration" would be a quick win until we figure this whole distributed streaming platform out. I would be inclined to simply create this category and put Kafka on it; but it would feel that only Kafka fits there. This is in fact a brand new category that we've been working with Kafka for the last 5 years and likely there will be a period of uncertainty about what this really means.

Regarding Pulsar, I am not sure if the project wants to fit in there. Maybe consult with the project owners?

**Comment by gunnarmorling** [comment]
>  I think adding Kafka Connect to "Integration" would be a quick win

Ok, fancy sending a PR for this then?

**Comment by riferrei** [comment]
Absolutely. I think I need to be added to the project. I just tried to push a branch and it failed for lack of permissions.

**Comment by gunnarmorling** [comment]
You can simply fork the repo to your own account, edit the file there and then send a pull request for including this change here. LMK if you need any help with that.

**Comment by riferrei** [comment]
Sure thing. Here it is: https://github.com/gunnarmorling/awesome-opensource-data-engineering/pull/7

**Comment by rk3rn3r** [comment]
Apache Kafka is an implementation of a distributed log. I think that's the correct term?

**Comment by riferrei** [comment]
> Apache Kafka is an implementation of a distributed log. So the PR is good to change that.
> But instead of "pub-sub" capabilities, would it maybe be better to name it "publisher-subscriber capabilities" to not confuse it with Google PubSub?

How about: "A distributed commit log with messaging capabilities"?

**Comment by gunnarmorling** [comment]
Sounds good. I'd only avoid the introduction of a new category just for Kafka itself. So if you'd remove that from your PR, change the description of Kafka as per above and keep the addition of Connect, I think it'd work?

**Comment by riferrei** [comment]
Agreed. Just made the changes :+1:

**Comment by gunnarmorling** [comment]
Applied, thanks!
